backend:
  name: github
  repo: lfuentesu/sute-jubilados
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "noticias"
    label: "Noticias y Comunicados"
    folder: "_noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Cuerpo de la Noticia", name: "body", widget: "markdown" }

  - name: "paginas_amigas"
    label: "Páginas Amigas"
    folder: "_paginas_amigas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Sitio", name: "title", widget: "string" }
      - { label: "Enlace Web (URL)", name: "url", widget: "string" }
      - { label: "Descripción o Nota", name: "description", widget: "text", required: false }
