backend:
  name: github
  repo: lfuentesu/sute-jubilados
  branch: master

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "editorial"
    label: "Editorial"
    folder: "_posts/editorial"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "cartas"
    label: "Cartas de Opinión"
    folder: "_posts/cartas"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "noticias"
    label: "Noticias"
    folder: "_posts/noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "humor"
    label: "Humor"
    folder: "_posts/humor"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen o Gráfico", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}